ARG FEATURES="otel"

FROM registry.access.redhat.com/ubi9/ubi:latest as builder

ARG FEATURES

RUN dnf install -y openssl openssl-devel cargo

WORKDIR /usr/src/myapp

COPY ./ ./

RUN cargo install --path ./gpu-pruner --locked --verbose --features $FEATURES

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest

RUN microdnf install -y openssl

COPY --from=builder /root/.cargo/bin/gpu-pruner /usr/local/bin/gpu-pruner

CMD ["gpu-pruner"]
