[package]
name = "gpu-pruner"
version = "0.1.0"
edition = "2021"

[dependencies]

resources = { path = "../resources" }

kube.workspace = true
k8s-openapi.workspace = true

tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
serde.workspace = true
serde_json.workspace = true

anyhow = "1.0.86"
prometheus-http-query = "0.8.3"
reqwest = "0.12.4"

clap = { version = "4.5.4", features = ["derive"] }
minijinja = "2.0.3"

secrecy = "0.8.0"