kind: Deployment
apiVersion: apps/v1
metadata:
  name: gpu-pruner
  namespace: your-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpu-pruner
  template:
    metadata:
      labels:
        app: gpu-pruner
    spec:
      volumes:
        - name: secret-volume
          secret:
            secretName: example-kubeconfig
            defaultMode: 420
      containers:
        - name: container
          image: 'quay.io/wseaton/gpu-pruner:latest'
          args:
            - 'gpu-pruner'
            - '-d'
            - '--run-mode=scale-down'
            - '--prometheus-url=https://thanos-querier-openshift-monitoring.cluster-url.svc'
          env:
            - name: KUBECONFIG
              value: /kube/config
            - name: RUST_BACKTRACE
              value: '1'
            - name: RUST_LOG
              value: info
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 250m
              memory: 64Mi
          volumeMounts:
            - name: secret-volume
              readOnly: true
              mountPath: /kube
          imagePullPolicy: Always
      restartPolicy: Always