kind: Deployment
apiVersion: apps/v1
metadata:
  name: gpu-pruner
  namespace: gpu-pruner-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpu-pruner
  template:
    metadata:
      labels:
        app: gpu-pruner
    spec:
      serviceAccountName: gpu-pruner
      containers:
        - name: container
          image: 'quay.io/wseaton/gpu-pruner:ubi9'
          args:
            - 'gpu-pruner'
            - '-d'
            - '--run-mode=scale-down'
            - '--prometheus-url=http://thanos-querier.openshift-monitoring.svc.cluster.local'
          env:
            - name: RUST_BACKTRACE
              value: '1'
            - name: RUST_LOG
              value: info
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 250m
              memory: 64Mi
          imagePullPolicy: Always
      restartPolicy: Always