kind: Service
apiVersion: v1
metadata:
  name: gpu-pruner
  namespace: gpu-pruner-system
  labels:
    app: gpu-pruner
spec:
  type: ClusterIP
  selector:
    app: gpu-pruner
  ports:
    - name: metrics
      protocol: TCP
      port: 8080
      targetPort: metrics
