apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gpu-pruner
  namespace: gpu-pruner-system
  labels:
    app: gpu-pruner
spec:
  selector:
    matchLabels:
      app: gpu-pruner
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
